### ISSUE TITLE
iOS crash on update installed

### ISSUE THREAD

**Issue by cris7hian30-df** [sweatco/react-native-code-push-diff#8]
The application has a crash when installing the codepush update with the library, in Android it works correctly.

Device
Model:iPhone 16 Pro
Orientation:Screen up

Operating System
Version:18.0.1
Orientation:Portrait
Jailbroken: No

Error:
Fatal Exception: RCTFatalException: Could not get BatchedBridge, make sure your bundle is packaged correctly
Could not get BatchedBridge, make sure your bundle is packaged correctly

RCTCxxBridge.mm - Línea 1187
-[RCTCxxBridge handleError:] + 1187

**Comment by gerdigitalfemsa** [comment]
@Augustach same error :( could you help us?

**Comment by gerdigitalfemsa** [comment]
RCTFatalException: Could not get BatchedBridge, make sure your bundle is packaged correctly - Could not get BatchedBridge, make sure your bundle is packaged correctly


<img width="1247" alt="image" src="https://github.com/user-attachments/assets/39b0313b-41ee-4654-b45a-afc4d2a72472">

@Augustach

**Comment by Augustach** [comment]
I cannot reproduce it on the example app, nor does it occur for the Sweatcoin apps.

Could you please attach the result of the `react-native info` command? I’m interested in which version of React Native you are using, whether you are on the new architecture or the old one, etc.

I should also mention that the iOS version contains the native code, so you cannot install the CodePush bundle on a binary version that does not link the `react-native-code-push-diff` library.

**Comment by gerdigitalfemsa** [comment]
**react native info:**

info Fetching system and libraries information...
System:
  OS: macOS 14.6.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 286.20 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v18.19.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman:
    version: 2024.09.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/german.martinez@digitalfemsa.com/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/german.martinez@digitalfemsa.com/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.14
    wanted: 0.72.14
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false
@Augustach 

thank you for your response.

**Comment by Augustach** [comment]
> iOS:
hermesEnabled: false
newArchEnabled: false

I suspect the reason it does not work on iOS could be due to `hermesEnabled: false`.

`code-push-diff release-react` and `code-push-diff bundle` build `hermes` bundle by default.
So could you please try updating `react-native-code-push-diff`  to 1.2.2 and make build for iOS with the `--use-hermes false` flag?

**Comment by gerdigitalfemsa** [comment]
@Augustach sure will try ok, we are going to share you the results.

**Comment by cris7hian30-df** [comment]
> > iOS:
> > hermesEnabled: false
> > newArchEnabled: false
> 
> I suspect the reason it does not work on iOS could be due to `hermesEnabled: false`.
> 
> `code-push-diff release-react` and `code-push-diff bundle` build `hermes` bundle by default. So could you please try updating `react-native-code-push-diff` to 1.2.2 and make build for iOS with the `--use-hermes false` flag?

Thanks for the comments, `--use-hermes false` worked for me, thanks for the update.
Can I close the issue? @Augustach

**Comment by Augustach** [comment]
> Can I close the issue? @Augustach

Sure, thanks for your reports.
Please do not hesitate to create new issues if you have any questions. I hope this library works well for you! 😄
